trigger:
  branches:
    include: [dev, test-me-*]
  tags:
    include: ['*']

# Run builds nightly to catch incompatibilities with new marshmallow releases
schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
      - dev
  always: "true"

resources:
  repositories:
    - repository: sloria
      type: github
      endpoint: github
      name: sloria/azure-pipeline-templates
      ref: refs/heads/sloria

jobs:
- template: job--python-tox.yml@sloria
  parameters:
    toxenvs:
      - lint

      - py35-marshmallow2
      - py35-marshmallow3

      - py36-marshmallow3

      - py37-marshmallow3

      - py38-marshmallow2
      - py38-marshmallow3

      - py38-marshmallowdev

      - docs
    os: linux
# Build wheels
- template: job--pypi-release.yml@sloria
  parameters:
    python: "3.7"
    distributions: "sdist bdist_wheel"
    dependsOn:
      - tox_linux
